### ISSUE TITLE
Breaking out the parsing

### ISSUE THREAD

**Issue by jwoertink** [graphql-crystal/graphql#12]
I noticed the Schema execute will take in the graphql, parse it, run it, then build out the result all in one go.

https://github.com/graphql-crystal/graphql/blob/1ee630fb4b0c3982285ecc6bc43fc1df98be60d3/src/graphql/schema.cr#L79-L99

Is there already a way, or would you be open to having the parsing portion broken out in to a separate public method? I'm thinking something along the lines of:

```crystal
# mutation Login($email: String!, $password: String!) {
#   login(email: $email, password: $password) {
#     email
#   }
# }
def parse(query : String) : GraphQL::Document
end

doc = schema.parse(query)

doc.operation_name #=> "Login"
doc.variables  #=> ["$email: String!", "$password: String!"]
doc.mutation? #=> true
doc.query? #=> false
```

Just a rough idea, but basically a way to ingest some GraphQL, and get back a usable object with what was passed in. Then from that point, the `execute` method could just take a `document` and run it.

```crystal
schema.execute(doc, variables, operation_name, context)
```

**Comment by jgillich** [comment]
What's the use case for this?

**Comment by jgillich** [comment]
My experience with Lucky is limited so correct me if I'm wrong, but while you could theoretically map Lucky operations and queries to GraphQL, I don't think you'd actually want to do this.

GraphQL objects are comparable to classes, each field can resolve to a primitive property or a method and it's possible to nest them, whereas I'm assuming you're returning primitive JSON-style values in Lucky queries/operations. See [this article](https://www.apollographql.com/blog/graphql/basics/graphql-vs-rest/). A simple query such as this has no equivalent in traditional REST APIs:

```
{
  book(id: 123) {
    author {
      books {
        title
      }
    }
}
```

The resolution hierarchy for this would usually look like this: `Query::book` -> `Author::books` -> `Book::title`; there are three classes involved rather than one.

What this library does is three things, it parses code to generate the schema/introspection data that is consumed by tools like [GraphiQL](https://github.com/graphql/graphiql/tree/main/packages/graphiql#readme), it generates resolver methods to take a query and turn it into the response, and it has a parser for the GraphQL language.

The first two aren't going to be of much use to you because they require the exact code structure laid out in the readme. You could take the parser and use it to write you own schema generator and resolver, but that's a lot of work only to end up with a constrained version of GraphQL.

**Comment by jwoertink** [comment]
Ah, I see. Thanks for the explanation! That makes things a lot more clear. It sounds like we may just have a really bad GraphQL setup with our app. None of us have ever used it before trying this new app, so it's super messy and clunky. I was hoping to find a nice pattern to clean it up and make it reusable, but I guess with how flexible GraphQL is, that's sort of the trade-off. You get more flexibility, but it's just a lot more difficult to setup 😅 

I'll probably hold off on doing a Lucky integration until I can pair up with someone that knows both Lucky and GraphQL 😄 I appreciate the feedback!
