### ISSUE TITLE
Using property/getter macros for GraphQL::Field

### ISSUE THREAD

**Issue by jwoertink** [graphql-crystal/graphql#18]
I can use methods with the `@[GraphQL::Field]` annotation, but using the `property`, or `getter` macros seems to fail.

It would be nice if we could do this

```crystal
@[GraphQL::Field]
property id : String?
```

vs

```crystal
@[GraphQL::Field]
def id : String?
  @id
end
```

This comes in handy when you have a `JSON::Serializable` object

**Comment by jgillich** [comment]
This is blocked by https://github.com/crystal-lang/crystal/issues/7504

```crystal
class Query
  @[GraphQL::Field]
  property id : String?

  macro finished
    {% for ivar in @type.instance_vars %}
      pp {{ ivar.annotation(GraphQL::Field).stringify }}
    {% end %}
  end
end
// => Nothing
```
Not sure if there is a workaround.

**Comment by Qard** [comment]
It works with `JSON::Serializable`/`JSON::Field`. Surely there must be a way to make it work. 🤔 

https://github.com/crystal-lang/crystal/blob/master/src/json/serialization.cr#L161-L177

**Comment by jgillich** [comment]
Interesting, accessing instance_vars inside methods does work, [but not inside `finished`](https://forum.crystal-lang.org/t/type-instance-vars-in-finished-macro/388). I believe `finished` is required, although I don't remember what the reason was. But I am getting weird errors when I try to remove them.

If anyone can show me how to remove `finished` from the current code I'd be happy add this.

**Comment by jgillich** [comment]
Good news, I found a way. Apparently there's a difference between macro expressions in methods (which have instance_vars available) and macros that define methods (which do not).
